"""Release notes shipped with every deployment — shown in Super Admin → Deployments.
Append a new entry (or extend the latest date) whenever a deploy-worthy change lands.
Bump BUILD on every deploy-worthy change so preview vs production builds are comparable."""

BUILD = "2026-07-15.8"
BUILD_TIME = "15 Jul 2026, 6:00 PM IST"

RELEASES = [
    {
        "date": "2026-07-15",
        "changes": [
            "Mira Studio websites got a quality overhaul 🖼️ — every photo now comes from a verified library matched to your business (watch stores get watches, clinics get clinics!), no more broken images; section headings adapt too ('Our Collection' for stores, 'Our Menu' for restaurants). Even websites you already built get auto-repaired",
            "Studio preview fixed + deploy options added 🚀 — the live preview now loads inside the studio, and every built website shows 3 clear deployment paths: hosted-by-Mira link, free self-hosting (Netlify/Vercel drag-drop), or your own custom domain",
            "Mira AI Studio now on the homepage 🏠 — a golden '✦ Mira AI Studio' link in the top menu plus a stunning 'Built with AI' showcase section with a live animated demo (watch a prompt turn into a website!) so visitors can discover the Studio and grab their 50 free credits",
            "Introducing Mira AI Studio ✦ (/mira.ai) — a brand-new platform where anyone can build a full website or business app from one sentence! Sign up for 50 free credits, watch Mira's agent team plan → design → code → test → deploy, get a LIVE URL in ~60 seconds, refine with prompts and download the full code. Credit top-ups via Razorpay",
            "Mira AI Studio wears couture 👗 — the studio page got a luxury redesign: gold & rose gradients, elegant serif headlines, glowing prompt box and a premium builder showcase that matches the Miracurl brand",
            "Your booking page just got smarter 💇 — guests now filter services by Everyone / Women / Men, and Mira's gender tags make sure men only see men's + unisex services (and vice-versa). Faster booking, fewer drop-offs",
            "One beautiful banner per category 🖼️ — no more uploading a photo for every single service! Each category (Skin, Manicure, Men Hair…) now has an elegant banner on the booking page with services as clean rows beneath. We've pre-loaded gorgeous defaults for all categories — change any of them from Service Menu → Banner",
            "Fully tune Mira's daily offer before posting 🎛️ — swap, remove or add services right on the suggestion card (tap ✕ on a service, or '+ Add / swap service'), and every price updates instantly with your chosen discount",
            "Package Builder upgrades 🎁 — Mira now picks gender-correct services (men's packages only get men's + unisex services, women's likewise), and a new '✎ Adjust %' under the package price lets you fine-tune the bundle discount with live price recalculation before publishing",
            "Service Menu redesigned ✨ — no more endless scrolling: instant search, one-tap category chips, and compact rows with quick online-booking toggles make editing your menu effortless",
            "Tune Mira's offer before you post it ✎ — a new 'Adjust %' selector on the Offer of the Day card lets you change the discount and see every service price recalculate instantly; tap 'Yes — use this offer' and the poster, caption and offer text are all rebuilt with YOUR chosen %",
            "Every email now carries your brand ✦ — all outgoing emails (reports, birthday wishes, review requests, alerts) end with a 'Book Now' button and a 'Powered by Miracurl' footer, turning every email into a booking opportunity",
            "Under the hood: engine room reorganised 🔧 — the backend was split from one giant file into 22 clean, domain-focused modules (customers, staff, billing, public booking, schedulers…). Nothing changes on screen, but future features ship faster and safer",
            "Locked out? Reset yourself 🔑 — 'Forgot Password' now emails a secure 1-hour reset link; setting a new password also clears any login lock instantly. Owners can still reset staff passwords from the Staff page",
            "Late staff auto-alerts ⏰ — 10 minutes after shift start with no check-in, staff get an automatic 'You're running late' email + a red banner and popup in their Staff Portal; owners receive a midday summary of the day's late arrivals",
        ],
    },
    {
        "date": "2026-07-14",
        "changes": [
            "HQ Security Snapshot 🛡️ — Super Admin's Security tab now shows a 7-day table of failed logins, PIN failures, PIN lockouts and rate-limit hits across ALL salons, with per-salon totals and a live event feed",
            "Security hardening 🛡️ — wallet balance check now needs the exact 10-digit number (with tighter limits) and shows only the balance; referral bonus crediting is race-proof; the test-data cleaner never touches customers with wallet money or invoices",
            "📣 Refer a salon, earn ₹1,000 ✦ — know a salon owner? Tap 'Share & earn ₹1,000' on your Dashboard's Miracurl Circle card and WhatsApp them your personal link. The moment they join Miracurl, ₹1,000 lands in your Circle bonus wallet!",
            "Referral amounts are now PIN-protected 🔒 — both the Miracurl Circle wallet and the Refer & Earn section in Settings need your Owner PIN before showing balances",
            "Miracurl Circle ✦ referral program — when a salon joins Miracurl through YOUR booking page, you earn ₹1,000! A PIN-protected Circle bonus wallet on your Dashboard shows earnings, and you get a congratulations email the moment your referral converts",
            "Leads now carry their source — HQ sees exactly which salon (and owner) referred every demo request, and the demo form greets visitors with 'As seen at [your salon]'",
            "Success Stories page 🌟 — a public marketing page (/success-stories) with live platform stats, salon win stories, real guest reviews and a free-demo request form that lands straight in the HQ Leads inbox",
            "Every booking page now sells for you 💼 — the footer says 'Powered by Miracurl — get this for your salon ✦' and links to the Success Stories page, turning every salon's guests into Miracurl leads",
            "Guest details are now validated ✅ — booking names accept letters only and mobile numbers must be a real 10-digit Indian number (+91 handled automatically), keeping your CRM clean",
            "Super Admin: Clean test data 🧹 — a per-salon cleanup tool scans for dummy bookings & customers (test names / invalid numbers), shows a preview, and removes them in one tap",
            "Fixed: the Day / Upcoming / Week buttons on Appointments (and Review filters) turned invisible when hovered — labels now stay readable with a clean white highlight",
            "About-Us shop poster 🏪 — new A4 print poster in the Flyer Studio: hero model, your logo, your salon story, 3 circular photos (from your gallery, or Mira creates them) and booking details",
            "Fixed: 'Have a wallet with us? — Check balance' on the public booking page wasn't responding — it now shows the guest's salon credit instantly",
            "Posters got a designer upgrade 🎨 — your salon LOGO now sits in a gold medallion on every poster, with an elegant script 'Exclusive Offer' flourish, serif headlines, a rotated '% OFF' starburst badge, sweeping ribbon curves and a styled contact bar",
            "Manage live packages 📋 — the Package Builder now shows exactly which packages are LIVE on your booking page (with a live counter), and one tap removes any of them so you can post an updated one",
            "Max 4 packages rule ✋ — your booking page never shows more than 4 packages; publishing a 5th is blocked until you remove one, keeping the page clean and focused",
            "Share the poster, not just words 📲 — 'Share on WhatsApp' now sends the glamour poster WITH the caption (on phones it opens the native share sheet; on desktop the poster downloads and WhatsApp opens ready to paste)",
            "Offer Maker quick-sets ⚡ — one tap applies 10-50% off to ALL selected services, and 3d/4d/7d/15d/30d chips fill the 'Valid till' date automatically",
            "Glamour posters 💗 — 6 stunning new AI poster styles (Pink Glam, Royal Gold, Bridal Blush, Emerald Luxe, Men's Edge, Festive Sparkle) with real model photography, your prices and booking link overlaid pixel-perfect",
            "Pick your poster look 🎨 — a style selector on the Day Offer card, Package Builder and Flyer Studio; leave it on 'surprise me' and Mira picks a fresh design each time",
            "Mira greets you with today's offer 📅 — the moment you open your Dashboard, Mira has already designed today's offer suggestion; just tap 'Yes — use this offer' to publish or 'Suggest another'",
        ],
    },
    {
        "date": "2026-07-13",
        "changes": [
            "Smarter review rewards ⭐ — 5★ reviews now earn ₹30 credit, 4★ earn ₹20 (auto-applied on the next visit), with a 'make it 5★ for ₹30' nudge",
            "Mira pre-writes the review ✍️ — tap 4★ or 5★ and Mira instantly drafts a personal comment from the guest's actual service & stylist; fully editable, and it doubles as their Google review after submit",
            "Monday auto-package suggester 📅 — when your package expires, Mira drafts a fresh one every Monday (audience rotates Men → Women → Family) and emails you; you approve & publish when ready — nothing goes live without your OK",
            "You control the offer 🎛️ — pick the exact discount % (5-50%) and the service tier (Premium: Color, Keratin, Botox / Budget crowd-pullers) before asking Mira; she calculates prices from YOUR choice",
            "Mira auto-rhythm 🧠 — left on 'Mira picks'? She reads your footfall: budget crowd-pullers when visits drop, premium high-margin deals on lean weekdays",
            "One tap = 3 platforms 🚀 — accepting a Day Offer (or publishing a Package) now auto-posts to Google Business, Instagram AND Facebook, with the flyer image",
            "Change offer & New poster — locked today's offer by mistake? Tap 'Change offer' to regenerate, or 'New poster' for a fresh flyer design without changing the offer",
            "Mira Package Builder 🎁 — one tap creates a Men's / Women's / Family package from your real menu, with your % and a validity window (3/4/7/15/30 days); expired packages vanish from the booking page automatically",
            "Your booking page sells more 💸 — signature packages & today's offer are now bookable in one tap, with a live 'Ends in 6h 32m' countdown and a wallet-balance checker for guests",
            "Prepaid Wallet / Membership 💳 — sell top-up plans (pay ₹5,000 → get ₹6,000 credit), track balances per customer, and bill against 'Salon Wallet' at the POS",
            "Birthday & Anniversary auto-offers 🎂 — wishes go out automatically with your gift offer; the dashboard shows today's celebrations with one-tap WhatsApp & SMS",
            "Staff targets & leaderboard 🏆 — set a monthly target + % per stylist; hit the target and the commission on their full business lands in the salary slip automatically",
            "Rate-your-visit funnel ⭐ — happy guests (4-5★) get a Mira-written Google review to paste in one tap; unhappy guests (1-3★) go to a PIN-locked private Complaints panel — never to Google",
            "Post History 📊 — new tab in Mira Studio showing every auto-post with its Instagram/Facebook likes & comments, so you know which offers pull customers",
            "Fixed: flyer posters on the live server had tiny text and broken ₹ symbols — fonts are now bundled with the app",
            "Fixed: public offer banner showed ₹0 as the original price",
            "Security hardening 🛡️ — daily AI usage quotas & durable rate limits on public endpoints, encrypted social-media tokens, and pinned OAuth redirect hosts",
        ],
    },
    {
        "date": "2026-07-12",
        "changes": [
            "Your public salon page got a glow-up ✨ — 3D floating lights, sparkles and neon service cards. Share miracurl-suite.com/salon/your-salon-name and impress every client before they even walk in",
            "Two apps, clearly split 📱 — customers installing from your booking/salon page now get the violet 'Miracurl Book' app; your business dashboard stays the emerald 'Miracurl Partner' app",
            "Hiring payments, automated 💰 — when a hired candidate's login is created, HQ is notified instantly and the salon owner receives a Razorpay payment link for the placement fee (amount now configurable by HQ)",
            "My Resume builder 📄 — Employee Portal staff fill their skills & experience once and download a polished PDF resume, with their verified Miracurl history included automatically",
            "Employee Portal 🧑‍💼 — registry-verified staff can now self-register at /employee with their mobile + Aadhaar, manage their profile, see employment history and apply to openings at any Miracurl salon",
            "Win them back 💌 — your dashboard now shows customers who haven't visited in 45+ days, with a one-tap WhatsApp nudge (pre-written message + 15% off) and a 30-day snooze",
            "Super Admin: Lead Gen Email 📬 — invite prospect salons to a demo with a designed email (12-agent AI team, live pricing, brochure + policy PDFs attached), open/click tracking, funnel stats and one automatic 5-day follow-up nudge",
            "Super Admin: Demo scheduler 📅 — prospects pick their preferred slot on a branded page; both sides get Google Calendar invites, and HQ gets a 🔥 notification + email",
            "Super Admin: Documents Center — download & share the tenant onboarding pack (Onboarding Policy, Hiring Policy, Suite Overview, T&C) as branded PDFs; the Suite Overview brochure now auto-attaches to every welcome email",
            "Super Admin: Platform Earnings chart — subscriptions + placement fees combined, last 6 months, with dues indicator",
            "Platform: security audit round 3 passed ✅ — CSV export hardening and rate-limited public tracking endpoints",
            "Marking a staff member as 'Left' now instantly blocks their salon app login (they keep access to the Employee Portal)",
            "Fixed: Mira's voice now stops speaking the moment you log out",
            "Mobile fix — the app header no longer overflows on phones: compact branch selector, icon-only salon switcher, and horizontal-scroll protection across every page",
        ],
    },
    {
        "date": "2026-07-11",
        "changes": [
            "Your salon now has its own public web page ✨ — share miracurl-suite.com/salon/your-salon-name with clients: your services & prices, star rating and best reviews, plus a Book Now button. Google can find and rank it too",
            "Super Admin: Notifications center — every hiring update, owner message, software lead, renewal alert and new signup in one filterable feed, with a jump-to-section on click",
            "Super Admin: the HQ console got a subtle 3D animated backdrop — floating orbs, rings and sparkles",
            "Platform: SEO pass — robots.txt, sitemap.xml (now including every salon's public page) and structured data for Google",
            "Platform: code-quality pass — Mira AI helpers extracted to a shared module (circular import eliminated), and 5 oversized functions (flyer composer, HQ ID card, receipt totals, salon signup, HQ digest email) refactored into small, testable units",
            "Platform: security audit round 2 — CCTV snapshot fetch now re-validates the connected IP (blocks DNS-rebinding SSRF), pending staff sign-ups are scoped per salon, and credential emails are HTML-escaped",
            "Platform: website — new neon 3D 'software flow' timeline on the landing page: the 7-step Miracurl journey from signup to auto-pilot revenue, with glowing animated cards",
            "Hire Staff 🧑‍💼 — post a hiring request from your dashboard and Miracurl HQ finds you verified candidates, schedules trials and updates you at every step",
            "Public Jobs board (/jobs) — HQ-verified professionals apply for open positions with their registered number; salon identity stays private until shortlisting",
            "Flash offers ⚡ — when AI CCTV spots chairs sitting empty, Mira alerts you on the Dashboard and designs a 2-hour flash offer with poster + WhatsApp caption in one tap",
            "What's New ✨ popup — after every update, salon owners see the latest features once, with a WhatsApp share button",
            "Renewal reminders on auto-pilot — owners get a branded email 15, 7 and 1 day(s) before their subscription/trial ends, with a direct Razorpay renew link",
            "Refer & Earn: referral list now shows reward status — pending until the referred salon makes its first payment, then ₹1,000 credited",
            "Mira Day-Smart Offers — ask Mira for today's offer: weekday-aware (fills chairs Mon-Thu, upsells Fri-Sun), built from your real service catalog, downloadable poster",
            "AI CCTV Analytics — waiting customers, empty chairs, queue length & idle staff read from camera frames every few minutes, with hourly trends",
            "Super Admin: Hiring tab (middleman pipeline: applied → shortlisted → trial → hired), renewals auto-email log with WhatsApp follow-ups, full Referral Tracking table",
        ],
    },
    {
        "date": "2026-07-10",
        "changes": [
            "Promo Video: Express mode now renders in seconds (was minutes / timing out on the live server)",
            "Promo Video: live timer — see exactly when generation started, how long it's running, and how long it took",
            "Promo Video: download history panel is now always visible on the right, with per-video Download & Delete",
            "Miracurl Team: new section for your own HQ staff & CEO — rose-gold company ID cards (MC-0001 style)",
            "Staff Verification: record staff of salons not using the software — public ✦ HQ Verified gold badge",
            "Staff Registry: salon owners can mark staff as 'Left salon' — moves to Past Staff, stays publicly verifiable",
            "Employee ID Cards: print-ready PDF cards for salon staff & verified staff, with blood group, barcode and a SCAN-TO-VERIFY QR code",
            "Billing: subscription plan catalog is now editable — change plan names & prices any time",
            "Deployments: this deployment history section, with server build status (compare live vs preview)",
            "Promo Video: Express now renders all scenes in a single ultra-light ffmpeg pass at social-friendly resolution — built for slow production CPUs",
            "Promo Video: AI Scenes mode fixed on the live server — renders at social resolution with low CPU priority so the server stays healthy mid-render",
            "Pricing: the public website pricing section now shows live prices from the plan catalog — edit a price in Billing and the website updates instantly",
            "Promo Video: new 'AI Booking demo' video — live walkthrough of Mira booking a Botox appointment (service, time, name) on the real app",
            "AI Posters: delete button next to download; website demo carousel refreshed with current app screens incl. Mira booking",
            "Website: partner testimonials are now real & editable from Super Admin → Partners",
            "Super Admin: new Diagnose tool per salon — see DB health, heavy data & stuck jobs, then 'Clear cache & auto-fix' remotely wipes the salon's device cache on next open",
        ],
    },
    {
        "date": "2026-07-09",
        "changes": [
            "Promo videos: removed email flow — direct download & delete from the studio",
            "AI Posters: contact details & website printed on generated posters; new AI Flyer studio for salons",
            "Platform: global API speed-up with GZIP compression",
            "Super Admin: Platform Load monitor and Database cleanup panels",
            "Mira Auto-Pilot: Monday marketing fully autonomous — weekly promo reel + AI poster auto-published to Meta",
        ],
    },
    {
        "date": "2026-07-08",
        "changes": [
            "Rose-gold rebranding across the app — new logo, favicon and downloadable Brand Kit PDF",
            "Dashboard aurora background animations",
            "Fixed promo video 'stuck forever' bug with automatic stale-job recovery",
            "Passed 2 security audits — security trust badges added to the /partner landing page",
        ],
    },
]
