"""Release notes shipped with every deployment — shown in Super Admin → Deployments.
Append a new entry (or extend the latest date) whenever a deploy-worthy change lands.
Bump BUILD on every deploy-worthy change so preview vs production builds are comparable."""

BUILD = "2026-08-18.82"
BUILD_TIME = "18 Aug 2026, 03:15 PM IST"

RELEASES = [
    {
        "date": "2026-08-18 (Talk to Mira on your salon page + human handoff 🎙️)",
        "changes": [
            "🎙️ 'Talk to Mira' on your public salon page — visitors can now start a voice or text conversation with Mira right from your profile page (previously only on the booking page); she knows your services, prices, staff and hours and can book appointments by voice",
            "🤝 Human handoff — when a guest asks for a real person, Mira politely confirms and shows one-tap options: call your receptionist, call the manager, or continue with Mira as their AI beauty advisor",
            "📇 Team contacts in Settings — new Receptionist number and Manager number fields in Settings → Salon profile power the handoff (falls back to your main salon number if empty)",
            "🕐 Instant hours reply — ask Mira about contact or timings and she shares your full day-wise working hours (from your Settings open/close times)",
            "🌙 After-hours smarts — outside business hours Mira never transfers to a human; she says the team is unavailable and offers to book or take a request for the team to call back",
            "🧠 Smarter handoff triggers — Mira also offers a human when guests are dissatisfied, ask for the manager, need special accommodation, or ask something she can't confidently answer",
        ],
    },
    {
        "date": "2026-08-17 (Smart phone search & country codes 🌍)",
        "changes": [
            "🔎 Type-to-find guests — while typing a number in Add Guest, matching saved guests appear instantly (name + number + country tag); one tap starts their bill. No more duplicate entries",
            "🌍 Country codes everywhere — phone fields now have a country selector (🇮🇳 IN +91 default, 20 countries) and the CRM shows every saved number with its flag, code and country tag",
            "🧹 Smarter matching — numbers saved with +91, spaces or dashes are now recognised as the same number in search, duplicate checks and the CRM",
        ],
    },
    {
        "date": "2026-08-14 (No duplicate guests, visit history & parallel bills 🧾)",
        "changes": [
            "📵 No more duplicate numbers — Add Guest now checks the phone number: if it's already saved, POS shows who owns it and lets you pick that guest for the bill in one tap (works when editing customers too)",
            "🕓 Visit history in CRM — tap the new clock icon on any customer to see every visit date-wise: which services, which stylist, how much, and how they paid",
            "🧾 Parallel bills — serve many guests at once! Tap '+ New bill' to start another bill while one is in progress; each bill shows as a chip (guest name + amount) and you can switch between them anytime. Opening POS in a new browser tab also starts its own fresh bill",
            "🔀 Merge duplicate guests — CRM now has a 'Merge duplicates' button that finds numbers saved more than once; pick the record to keep and all bills, visits, wallet money and points move into it, so the full payment history stays in one place",
        ],
    },
    {
        "date": "2026-08-14 (Billing fixed & bills that never vanish 🧾)",
        "changes": [
            "🚑 POS billing FIXED — the 'Create' and 'Create & Complete' buttons were silently failing (a code error stopped every click); bills now punch instantly and the receipt popup appears every time",
            "⚠️ Duplicate-bill warning is now a proper in-app popup — 'Possible duplicate bill … Yes, bill again / Cancel' shows reliably on every device (the old browser confirm box was blocked on installed apps)",
            "📋 Your bill follows you — add items, jump to any other tab and come back: the POS asks 'Pending bill — Continue or Discard?' so an in-progress bill is never lost",
            "🗑️ Safer open-bill delete — the delete button now asks for a second confirming tap (turns red with 'Confirm?') instead of a browser popup that could be blocked",
            "✅ Popup sweep — cancelling an appointment, deleting/disabling staff, resetting a staff password, creating a staff login and deleting inventory products now all use beautiful in-app confirmation dialogs that work on every device, including the installed apps",
            "🛡️ Full popup sweep — EVERY confirmation across the app (customers, services, reviews, geo-fence, wallets, branches, managers, staff portals, gift cards, and the entire Super Admin console) now uses the same reliable in-app dialogs — nothing can silently fail on installed apps anymore",
            "✂️ Overall % discount — the POS overall-discount box now has a ₹/% toggle: tap % and type 10 to knock 10% off the whole bill (still capped so it can never exceed the bill)",
            "💅 Polished billing bar — coupon and discount controls are now neat grouped pills, active discounts show as colour-coded chips, and the Grand Total sits in a bold gold-on-black badge",
        ],
    },
    {
        "date": "2026-08-14 (Branch pins, your salon hours & under-the-hood tune-up 🛠️)",
        "changes": [
            "📍 Branch pins on Attendance — every staff member (including new hires) now shows their branch location right under their name in the roster, so you always know who works where",
            "🕐 Your salon, your hours — set your exact Open & Close times in Settings → Salon profile; the public booking page automatically offers slots only inside those hours",
            "🗓️ Working-hours label — the hours text you save (e.g. 'Mon–Sun · 10 AM – 9 PM') shows on your public booking page so guests know when to visit",
            "🛠️ Engine tune-up — a full code-quality audit was completed: billing, WhatsApp cards, Mira chat, lead engine, gift-card campaigns and email delivery were streamlined and re-verified with 66 automated regression tests, so everything runs exactly as before, only cleaner and safer",
        ],
    },
    {
        "date": "2026-08-13 (Grow & get found 🚀)",
        "changes": [
            "🎁 Refer & Earn upgraded — invite another salon and get 1 FREE MONTH added to your subscription automatically after their first payment (Settings → Refer & Earn or the /refer page)",
            "📣 Referral nudge — the dashboard now celebrates when a salon signs up with your link and reminds you a free month is one payment away",
            "📰 New public Blog at /blog — practical salon-growth articles that rank on Google; Super Admins can publish articles or let Mira draft one from just a topic line (✦ Draft with Mira)",
            "📊 'Trusted by salons across India' strip on the website — live platform numbers (salons, bookings, bills) build instant trust with visitors",
            "🏷️ Offer flyers you control — publish any Offer Maker flyer to your booking page's new 'Current offers ✨' section, set an expiry date so it drops off automatically, with a '⏳ X days left!' countdown ribbon",
            "📅 Week-off change requests — staff request a new week-off day (Mon–Thu only, never Fri/Sat/Sun), owners approve in Attendance; approved changes start the next day and check-ins on a week-off day ask for owner confirmation",
            "📈 Weekly Revenue & Staff Business tables in Reports — see week-by-week income and exactly how much business each staff member brought in",
            "🧠 Mira answers period questions correctly — 'How much business last week?' now returns the true figure with your top performer's name",
            "⚡ Instant Mira replies on the booking page — price list, timings, address and contact answered in milliseconds; strict privacy guard (never shares owner/staff personal info) and warm welcome-back greetings for returning clients by phone number",
            "✨ Gold-plated sidebar tabs — the admin menu now wears the metallic gold pill on the active tab with a gold hover on every other tab",
            "🤖 Mira's new look — tap her avatar on the dashboard and she speaks today's collection, bookings and staff on the floor; the AI Assistant page got live stat chips and grouped quick-ask prompts",
            "🔗 Outreach emails now carry trust links — Website, Features, Pricing, About Us and Contact — plus better Google indexing (sitemap + organization schema)",
            "↻ Gentle updates — when a new version ships, you'll see a small 'Miracurl just got better ✨' toast with a Refresh button instead of the page reloading on its own",
            "🧾 Faster bill fixes — desk staff can now edit Recent Invoices themselves (no Owner PIN needed); every edit stays fully audited. Voiding a bill still needs the PIN",
            "🔓 Reports opens PIN-free — the Owner PIN popup no longer appears when staff open Sales Reports; only the Per-Stylist Commission card stays locked until you tap 'Unlock with Owner PIN'",
            "🤝 Managers can hire — the Hire Staff section no longer asks managers for the Owner PIN; post openings, review applications and manage requests freely",
            "💬 WhatsApp confirmations, polished — a beautifully formatted confirmation message (salon name, service, date, time, stylist, amount) that opens the guest's chat DIRECTLY using their saved number — no more 'Send message to' search, and no more broken � symbols",
            "🖼️ Designed confirmation card — a gold-on-black appointment card image staff can open with one tap and attach in WhatsApp; owners control it with the new 'Staff WhatsApp: Direct/Approval' toggle on the Appointments page",
            "📝 Weekly auto-article — every Monday Mira drafts a fresh salon-growth blog article; Super Admins just review and tap 'Approve & Publish' to keep Google fed",
            "📱 Phone required on booking — new guests must have a 10-digit phone number, and booking a legacy guest without one asks for it right in the form, so every WhatsApp confirmation reaches the right chat",
            "🗓️ Smarter booking calendar — the public booking page now opens on TODAY, past dates are blocked, slots that already passed grey out automatically, and bookings stay within salon hours (10 AM – 9 PM)",
            "🛡️ No more double bills — the POS Create buttons stay disabled until a payment mode is selected and lock instantly while a bill is being created",
            "👯 Duplicate bill alert — if an identical bill for the same guest was punched in the last 3 minutes, staff get a warning and must confirm before it's created again",
        ],
    },
    {
        "date": "2026-08-08 (New brand, new website ✨)",
        "changes": [
            "✨ New Miracurl Suite gold logo across the website — header, hero and footer, with the 'Manage. Automate. Grow.' identity",
            "🧭 Professional navigation — Home, About Us, Mira AI Studio, Features, Pricing, Staff Verification, Contact Us, Sign In & Sign Up, with real pages at /features, /pricing, /about-us and /contact-us",
            "📇 Contact Us dropdown & page — email, WhatsApp, Instagram/Facebook and a 'Who can use Miracurl' list (salons, spas, boutiques, barbershops, nail & bridal studios and more) + a Request-a-callback form",
            "👤 Meet the Founder section — CEO photo, story and social links on the home page",
            "📱 Fresh gold app icons for both mobile apps — Miracurl Book & Miracurl Partner now install with the new gold MS icon and a golden status bar",
            "🗂️ New 'Who Can Use' page — every business type (salons, spas, boutiques, barbers, nails, bridal, tattoo, wellness) with its own photo card",
            "🤖 Mira got a face — her golden avatar now fronts the Ask Mira chat and the Need-help callback card that collects name, phone & email for the team",
            "🙈 Payment privacy — tenant UPI IDs are masked on gift card & membership pages (copy button still gives the full ID), and right-click is blocked site-wide",
            "Super Admin: New 'Website & CEO' tab — edit the public site's contact email, social links and CEO profile; changes go live instantly",
            "🥇 Golden-white locked header on the Staff Verification portal — same premium brand on light pages",
            "🪙 Brand watermark on AI posters — every AI-generated social post, offer flyer and promo image now carries a subtle gold MS monogram in the corner, so your brand travels with every share",
            "✨ Shining gold logo — the Miracurl Suite wordmark now has a moving metallic shine, and the golden-white header is live on Jobs Board, Salon Finder, Partners, Book-a-Demo and Candidate pages too",
        ],
    },
    {
        "date": "2026-08-08 (Google Wallet cards, open bills & fair attendance ⏰)",
        "changes": [
            "📱 Add to Google Wallet — members and gift card holders can now save their card straight into Google Wallet from the purchase page and card emails; it shows up like a real card on their phone",
            "🧾 Open Bills at POS — started a bill but the guest stepped out? Park it and pull it back anytime; owners also get an unbilled-bills panel in Reports and an automatic end-of-day open-bill alert email",
            "🎁 Sell gift cards right from the POS billing tab — walk-in buyers can now purchase a gift card at the counter in seconds",
            "🔔 QR scan sounds at POS — a pleasant chime on a successful member scan and a buzz on an invalid/expired card, so staff never miss a scan result",
            "📲 Instant renew at POS — when an expired member scans, staff get a one-tap 'WhatsApp renew link' button to send the guest their renewal page immediately",
            "⏰ Fair late-arrival rules — Mon–Fri check-ins get a 10-minute grace period (no grace on weekends); fines flow automatically into the monthly salary slip",
            "📧 Weekly Late Arrival Digest — every Monday, owners get a summary of who came late and total fines, each late staff gets their own gentle summary, and the most punctual staff member is celebrated with a 🏆 Punctuality Star shout-out",
            "↩ Mistake-proof attendance — staff see a confirmation before checking out, admins can undo an accidental check-out, and a wrongly waived late fine can now be un-waived too (owner PIN protected, full audit trail)",
            "🪪 Role badges everywhere — Super Admin, Manager and Admin labels now show clearly across the console, plus a unified notification feed in the bell dropdown",
            "🔐 Fingerprint/passkey login fixed for the www domain — re-register your fingerprint once if it was set up earlier",
            "🛡️ Manager PIN lock hardened — locked sections now show a clear 'Sorry, you're not authorized' popup with Enter PIN / Cancel options (Cancel returns them to the previous page); sections NO LONGER auto-open when the owner hasn't set a PIN, and every PIN-protected action validates the PIN strictly (4–8 digits, wrong attempts logged & rate-limited)",
        ],
    },
    {
        "date": "2026-08-07 (QR scan, WhatsApp cards & a stunning membership page 💎)",
        "changes": [
            "📷 Camera QR scan at POS — tap Scan next to the Membership box and point the camera at the member's card QR; the guest is pulled up instantly",
            "💬 WhatsApp card delivery — a one-tap WhatsApp button next to every member (Offers & Plans → Memberships) sends their card link, Member ID and validity; buyers also get a 'Save my card on WhatsApp' button right after purchase",
            "💎 Membership page redesigned — medallion tier badges, MOST POPULAR / BEST VALUE ribbons, each plan's full benefit list (edit benefits & free services per plan in Offers & Plans), validity shown on every card, and a polished Member Details + Payment Summary checkout",
        ],
    },
    {
        "date": "2026-08-07 (Wallet Pay at POS 💰)",
        "changes": [
            "💳 Membership row on the bill — right under Gift card, staff can type/scan a Member ID (MC-…) and Apply: the guest is pulled up instantly with their tier, auto-discount, cashback % and wallet balance shown (expired members get a renewal prompt)",
            "💰 Wallet Pay at POS — when a guest has wallet balance, a one-tap 'Pay from wallet' button appears in Payment Details: covers the whole bill if the balance is enough, or applies the full balance and collects the rest via cash/card/UPI",
            "🧾 Receipts now show '💰 Paid from wallet' as its own line so guests see exactly how their balance was used",
            "💎 Membership plan cards redesigned — tier badges, 'MOST POPULAR' and 'BEST VALUE' ribbons, benefit checklists and glowing selection states",
        ],
    },
    {
        "date": "2026-08-07 (Membership power-ups 💳)",
        "changes": [
            "🔎 POS Member Lookup — type or scan a Member ID (MC-…) in the guest box and the member is pulled up instantly, with their plan, discount and cashback shown; expired members trigger a renewal prompt",
            "🔍 POS service search rebuilt — results now appear right at the top with a match count and category tags; multi-word searches like 'fruit facial' match across ALL categories, ignoring hyphens and extra spaces",
            "📲 App updates now reach installed phones faster — the app checks for new versions every time it's opened, so new features appear without reinstalling",
            "📊 Reports now include a Premium Memberships card — total & monthly sales, active members by tier, online vs at-salon split, expiring-soon count, cashback credited and outstanding wallet liability",
            "🎂 Member birthdays got special — active members automatically receive a golden birthday email with their member perks and a one-tap booking link (regular guests still get the classic birthday wish)",
        ],
    },
    {
        "date": "2026-08-06 (Premium Membership launch 💳)",
        "changes": [
            "💳 Premium Membership is live — guests can buy Silver ₹5,000 / Gold ₹7,000 / Platinum ₹10,000 / Diamond ₹15,000 / Custom ₹5,000+ (12 months) right from your public booking page, paying by card or UPI",
            "🪪 Every member gets a Member ID (MC-XXXX-XXXX-XXXX), a luxe digital membership card with QR, and a polished welcome email with the card PDF attached",
            "💰 Wallet cashback on every bill — each plan's % lands straight into the member's wallet, spendable on any future visit; plans can also carry a service discount %",
            "🔍 Scan the member QR (or open /member/ID) to instantly verify name, plan, status, expiry, wallet balance and points — with Renew and Download Card buttons",
            "🧾 Offers & Plans → Memberships now shows ALL onboarded members — salon-sold (POS) and customer-purchased (online) — plus UPI payments awaiting your approval",
            "⏳ Automatic expiry reminders — members get a renewal email 7 days and 1 day before their card expires, with a one-tap renew link that extends from their current expiry",
            "⚙️ Plans are fully yours: edit price, cashback %, service discount %, benefits list, and choose which plans sell on the booking page",
        ],
    },
    {
        "date": "2026-08-06 (Temporary staff transfers, POS upgrades & smarter notifications)",
        "changes": [
            "🔁 Temporary staff transfer — send any staff to your other salon for exact dates (even just 1 day); they bill, check in and log in there, then return home AUTOMATICALLY after the last day",
            "🧾 Temporary Duty Log on the Staff page (admin-only) — see who worked at which salon, the dates, and exactly how much business they billed there",
            "🔔 One-time notification popup after login — the staff member and managers of BOTH branches are informed when a temporary duty starts and when it ends; you choose in-app only, + email, or + SMS at transfer time",
            "👨👩 Services categorized for Men / Women / Unisex — filter chips on the Services page and in POS billing, one-tap re-categorize on any service, and a 'Who is it for?' picker when adding services",
            "📖 Public booking page: the Everyone / Women / Men tabs now follow YOUR categorization from the Services page — guests instantly see the services meant for them",
            "✏️ POS price is now editable per bill — haircut listed at ₹700 but charging ₹800 today? Just type the new price on the bill line",
            "🔎 POS search fixed — typing 'Threading' (or any service) now finds it across ALL categories, not just the selected one",
            "📅 CRM now shows when each customer was added, with one-tap Today / Yesterday / Last-7-days filters — newest guests always on top",
            "🧾 Receipt popup redesigned — long bills scroll smoothly while the Total stays locked at the bottom with the action buttons",
            "🔒 Protected sections got stricter — a wrong Admin PIN now returns managers to where they came from (attempt logged for the owner), with a clear Go-back button",
            "✨ New transfer confirmation popup — staff photo, from → to salons, dates and exactly what will happen (replaces the plain browser alert)",
            "💬 Buy SMS points right from your Dashboard — a balance strip (turns amber when low) with one-tap Razorpay top-up packs",
            "Platform: Trial salons now get automatic day 5/10/13 nudge emails with usage stats + a one-tap activation pay link (plan pricing follows Super Admin overrides)",
        ],
    },
    {
        "date": "2026-08-05 (Leave, week-offs & review requests that reach everyone)",
        "changes": [
            "🌴 Staff can now apply for leave from their portal (from–to dates + reason) and admins Approve/Reject right on the Attendance page — approved staff show 'On leave' automatically",
            "📅 Admins can directly mark any staff on leave (from-date to to-date) — they disappear from the booking page and show 'On leave' for those exact dates",
            "🏖️ Week-offs respected everywhere — staff on their weekly off show a 'Week off' badge (not 'Not checked in'), get no late-arrival emails, and are greyed out on the booking page for that day",
            "⭐ Pending Review Requests fixed — walk-in POS bills now count (was 0 for salons that bill without appointments), so every recent guest appears for a review ask",
            "📨 Review requests by SMS, WhatsApp & Email — managers send by SMS; owners/admins get all three buttons per customer",
            "📥 Reply Inbox in Super Admin → Mira Lead Agent — every lead reply appears with its full message and a one-tap reply link",
            "💵 US clients now see $ USD plans and pay by card via Stripe on payment links; Indian salons keep ₹ Razorpay",
            "🗂️ Super Admin Tenants page redesigned into clean, readable cards per salon",
            "✉️ Cold outreach made inbox-friendly — one-click unsubscribe, no attachments, human sender name (better deliverability to US clients)",
        ],
    },
    {
        "date": "2026-08-02 (Branch dashboards restored & location made easy)",
        "changes": [
            "🚑 Branch dashboards fixed — attendance board, active staff, check-in details and This-Month revenue now show correctly for the Main salon and every branch (records with older branch tags are counted under the Main salon automatically)",
            "📍 Set your salon location by simply pasting a Google Maps link — or just typing your salon name + area (e.g. 'Miracurl Salon Marathahalli'); works for the Main salon and each branch from the Attendance page",
            "🗺️ Live map preview — the GPS check-in fence card now shows the exact pinned spot on a real Google map so you can visually confirm it's right, with an 'Open in Google Maps' link",
            "🏠 Clear salon names everywhere — 'Main salon' is now shown as your actual salon name + location (e.g. 'Miracurl Unisex Family Salon — Marathahalli') across staff cards, reports, attendance, manager dropdowns and the top bar",
            "🧑‍💼 Manager check-ins fixed — staff assigned to a branch are geo-fenced to that branch's exact location; the staff portal now shows each person exactly which location they must check in from",
            "✏️ Branch renames are safe now — renaming a branch automatically carries over all its staff, manager logins and past bills, so reports never go blank after a rename",
            "⚙️ Settings fix — the 'Google Maps location link' in Salon Profile now saves AND loads back correctly, and saving it also pins your salon's GPS check-in fence in one step",
            "🔔 This 'What's New' popup now appears for manager logins too, so your whole team knows what changed after every update",
        ],
    },
    {
        "date": "2026-07-29 (Preview before you pay & call controls)",
        "changes": [
            "📲 Customer SMS everywhere — booking confirmations (online & in-salon bookings), billing receipts and 24-hour reminders now go out by SMS for every salon (each SMS uses 1 SMS point — ask HQ to top up your balance)",
            "🪪 Staff verify fix — phone numbers entered with +91 now find the staff member correctly in the public registry",
            "⏱️ Half-day rule — staff who don't check in within 3 hours of shift start are auto-marked half-day with the deduction (half of one day's salary) applied in payroll; approved leaves & week-offs are skipped",
            "📷 Desk QR check-in — print the new QR from the Attendance page; staff scan it at the salon desk to check in instantly when GPS fails (works in the staff portal too)",
            "↩️ Half-day waive — wrongly-applied half-day marks can be reversed with one tap on the Attendance page (owner PIN protected, full audit trail)",
            "🔒 Stronger sign-in — untick 'Keep me signed in' at login and your session ends when the browser closes, so shared computers always ask for the password",
            "⏰ Renewal reminders & grace — paid salons now get the same gentle popup in the last week before their subscription ends and during the courtesy grace period; after grace runs out, login shows a clear 'subscription expired — contact the Miracurl team' message",
            "💌 Renewal nudge email — 7 days before your subscription ends, you automatically receive a one-tap Razorpay renewal link by email, matched to your current plan",
            "📖 Smoother booking — the online booking page now scrolls to the top automatically at every step, and the staff verify portal asks for the badge name right where you need it",
            "Super Admin: 🎥 60-second walkthrough video (real app screens) auto-included in every WhatsApp lead pitch and inquiry reply — now with Mira's voice narration, plus a full 2-minute feature tour at /miracurl-full-tour.mp4 ready for YouTube",
            "Super Admin: 📈 Payment-link conversion tracker — see Sent / Opened / Paid / Conversion % at a glance, with an 'opened' chip on every link the owner has viewed",
            "❌ Cancellation SMS — customers automatically get a text when their booking is cancelled, with an invite to rebook",
            "Super Admin: 📜 SMS delivery log — tap any salon's SMS balance to see every text sent, failed or skipped, with reasons",
            "Super Admin: ⚠️ Low-balance alerts — HQ gets an email when a salon's SMS points drop under 20, plus WhatsApp lead pitches now include the live demo, salon signup, staff registry and screens-tour links",
            "🔐 Security hardening (full audit passed) — staff-portal password resets now require a 6-digit email verification code (Aadhaar alone is no longer enough), public registry phone lookups need the staff member's badge name, and the salon-isolation layer got an extra fail-closed lock so no salon can ever see another salon's data",
            "📊 Honest dashboard numbers — 'Total Customers' now counts only real CRM guests (hidden incomplete public-booking entries no longer inflate it), and 'Pending Review Requests' shows exactly the recent completed visits the review blast would reach",
            "Super Admin: 🧹 Deep clean upgrade — the per-salon cleanup now also finds 'ghost guests' (never completed a visit, no upcoming booking) and orphan bookings whose customer was deleted; wallet/invoice customers stay fully protected",
            "💌 Gift card email preview — buyers can now see the exact e-card email (design, quote & message) before they pay, straight from the gift card page",
            "🪪 Staff Registry fix — the Badge PDF button on your Staff Registry page downloads instantly again (no more 'enter the staff member's name' error)",
            "🔊 Hear it again — replay Mira's daily greeting on the Dashboard anytime with the new replay button, plus a Stop control while she speaks",
            "Super Admin: ⏰ Reschedule Mira's queued calls — move any scheduled lead call to a new time instead of cancelling it",
            "Super Admin: 💳 Per-tenant subscription payment links — pick a plan or a custom deal price, copy the link or send a designed onboarding email; the salon pays via Razorpay and their plan activates instantly. HQ gets an instant 'salon just paid' email, and Mira auto-reminds owners 2 days before an unused link expires",
        ],
    },
    {
        "date": "2026-07-28 (Gift card glow-up & stability)",
        "changes": [
            "💌 Beautiful occasion gift cards — every occasion (Diwali 🪔, Birthday 🎂, Valentine's ❤️ …) now carries its own heartfelt quote, a 'Why you'll love this salon' section and a warm sign-off",
            "🙏 Buyers get a heartfelt 'Thank you for choosing us' email after gifting",
            "⏳ Gift cards nearing expiry now remind the recipient 7 days before, so no balance goes to waste",
            "🗑 Clear finished gift-card history (cancelled/expired/redeemed) — Owner-PIN protected",
            "🏢 'Request more branches' now asks how many you need and sends HQ a clean request — HQ replies with a payment link, then unlocks your new limit",
            "🔒 UPI 'I have paid' stays locked until a transaction ID or payment screenshot is attached — cleaner proof for salons",
            "🛡 Fixed the browser-crash on Super Admin login — Mira's voice now activates only when you tap her mic",
            "📅 Gift card dates now read naturally (e.g. '23 Jan 2027') and follow your validity setting exactly",
        ],
    },
    {
        "date": "2026-07-27 (Gifting, reorder & owner security)",
        "changes": [
            "💬 WhatsApp gifting — buyers can add the recipient's WhatsApp number and send the gift card straight to their chat after payment (also from the receipt email)",
            "↕️ Category reorder — drag your service categories into any order; the Services page and your public booking page follow it instantly",
            "📊 Gift card analytics — Settings → Gift Cards now shows a 6-month sales vs redemptions chart plus balances expiring each month",
            "✨ Mira paints new services too — 'Let Mira paint this' now works while creating a service, and painting runs in the background so slow connections never error out",
            "🔔 Notifications you can clear — Super Admin notifications mark as read on click, can be dismissed, with a one-tap 'Mark all as read'",
            "🔐 Owner PIN lock — Settings and Staff now ask for your Owner PIN on shared devices (set the PIN in Settings → Security)",
            "🏢 Branch limits — salons can add locations only up to their paid branch allowance; Miracurl HQ raises the limit after payment",
            "🎨 Polish — branch dropdown matches the dark header, and the Day/Upcoming appointment tabs no longer shift around",
        ],
    },
    {
        "date": "2026-07-26 (Category editing & service disable)",
        "changes": [
            "✏️ Rename categories — open a category's Banner and rename it; every service and the banner move with it instantly",
            "🚫 Disable services — a new Active toggle on every service row; disabled services grey out with a badge and vanish from the booking page until you re-enable them",
            "🏆 Weekly Win Report — every Monday morning Mira emails HQ a summary of the week: calls made, answered, demo requests, callbacks kept, new leads, emails sent and who's heating up",
        ],
    },
    {
        "date": "2026-07-25 (Service Menu redesign)",
        "changes": [
            "🔎 Premium search bar — bigger, rounded, with a search icon, clear button, ⌘K / Ctrl+K shortcut, and instant results with a smooth 250ms debounce across names, categories and descriptions",
            "🏷️ Modern category chips — rounded pills with icons, live service counts, hover lift and a rose-pink active glow; scroll them sideways on small screens",
            "🔄 New categories appear instantly — chips are built live from your services and banner categories, counts stay in sync without any refresh, with elegant loading and empty states",
        ],
    },
    {
        "date": "2026-07-25 (Dedicated Salon Mira)",
        "changes": [
            "🎙️ Every salon now has its own Mira — a dedicated AI manager in the dashboard (amber-rose mic button): she greets with today's bookings, revenue and new customers, answers questions hands-free, gives promo ideas, and even opens the right page for you",
            "🗣️ Salon Mira speaks English or Hindi (हिं/EN toggle) and keeps the conversation going until you say 'stop'",
            "🎧 Booking-page voice fix — Mira no longer answers in Hindi when customers speak English (the speech recognizer was being biased toward Hindi script)",
        ],
    },
    {
        "date": "2026-07-25 (Mira Photo Studio & Logo polish)",
        "changes": [
            "✨ Mira Photo Studio — hit 'Mira Photos' on the Service Menu and she paints an elegant on-brand photo for every service that has none, matched to its category (8 per run); or open any service and tap 'Let Mira paint this'",
            "🎨 Logo polish — the Miracurl mark in the Super Admin header now sits on its dark brand circle (no more white disc), and salon logos in the sidebar get a framed dark backdrop",
        ],
    },
    {
        "date": "2026-07-25 (Services & Uploads polish)",
        "changes": [
            "⚡ Faster image uploads — photos are compressed harder before upload, storage hiccups (503) are retried automatically, and uploads no longer slow down the rest of the app",
            "🔎 Smarter service search — typing partial words like 'mthrea' now finds 'Men Threading'; search also looks in categories and descriptions",
            "🎨 Fixed the browser tab icon — the Miracurl logo now sits on its dark brand circle instead of a plain white disc",
        ],
    },
    {
        "date": "2026-07-25 (Lead-Local Call Timing)",
        "changes": [
            "🌏 Mira now calls every lead during THEIR business hours — a New York spa gets called in New York's daytime, a Pune salon in India's, using the phone country code (and US area-code time zones)",
            "🕙 Bulk calls & retries are smart — leads currently outside their local window aren't wasted; they're auto-scheduled for their next 10 AM local time",
            "☎️ Morning callback redials and timed callbacks also follow the lead's local clock",
        ],
    },
    {
        "date": "2026-07-25 (International Dialing Fix)",
        "changes": [
            "🌍 Correct country codes — lead phone numbers are now stored in full international format, so US/overseas salons (New York spas etc.) are dialed with +1 instead of wrongly getting +91. Existing leads are auto-corrected once on startup",
            "🔁 Weekly heat refresh also upgrades any remaining national-format numbers to international",
            "🎧 Call History now explains that recordings appear only on answered calls — failed and unanswered calls have no audio",
        ],
    },
    {
        "date": "2026-07-25 (Security Hardening)",
        "changes": [
            "🔐 Twilio webhook signatures — every voice webhook (pitch, conversation, status, recording) now cryptographically verifies Twilio's X-Twilio-Signature, so nobody can forge call events",
            "🛡️ Recording proxy locked down — recordings are only fetched from genuine twilio.com hosts with redirect protection, so account credentials can never leak to a third-party server",
            "🙈 DB explorer redaction — password hashes and secrets are masked in the Super Admin database explorer",
        ],
    },
    {
        "date": "2026-07-24 (Callback Memory & Heat Alerts)",
        "changes": [
            "⏰ Callback time memory — when an owner says 'call after 4 PM' (or 'कल शाम को'), Mira notes the exact time and dials back precisely then (8 AM–9 PM), not just next morning; the requested time shows in Call History",
            "🔥 Hot list alerts — after the weekly heat refresh Mira announces the leads whose scores jumped ('top mover: X jumped from 55 to 75 — worth a call!') in her greeting, and knows them when you ask",
        ],
    },
    {
        "date": "2026-07-24 (Hindi HQ, Heat Refresh & Callbacks)",
        "changes": [
            "🗣️ Hindi HQ assistant — speak or type to Mira in Hindi (or Hinglish) and she replies in Hindi; tap the हिं/EN button in her header to switch her listening language",
            "🔥 Weekly Lead Heat Refresh — every Sunday Mira re-checks each lead on Google (reviews, rating, website, phone) and re-scores them so the hot list always shows the freshest opportunities",
            "☎️ Callback Scheduler — leads who said 'call me later' are automatically re-dialed the next morning at 10:30 AM, once, so no warm lead goes cold",
        ],
    },
    {
        "date": "2026-07-24 (Wake Word, Hindi & Node Pulses)",
        "changes": [
            "👂 Wake word — just say 'Hey Mira' anywhere in the Super Admin console and she wakes up, greets you and starts listening (toggle it with the 👂 button in her header)",
            "🇮🇳 Hindi pitch — Mira's sales calls now speak Hindi: owners press 3 for the full Hindi pitch and menu, or simply reply in Hindi and she switches mid-conversation; their preference is remembered for future calls",
            "💥 Map node pulses — when Mira announces a live event on the Platform Map, the matching module card flashes brightly in sync with her voice",
        ],
    },
    {
        "date": "2026-07-24 (Smarter, fresher Mira)",
        "changes": [
            "🌅 Correct greeting always — 'Hey Miracurl! Good morning / afternoon / evening' now follows the actual IST time (the stale cached greeting bug is gone), and her AI answers know the current time too",
            "🧹 Fresh conversation on every tap — tapping Mira clears the old chat and greets you fresh: 'Hey Miracurl! Good morning! … How may I help you today — what details do you want me to show?'",
            "🧠 Proactive issue alerts — if all calls failed she says it straight: 'I tried calling 25 leads today and NONE connected — Twilio trial blocks unverified numbers. Once fixed, say retry failed calls'",
            "🗣️ 'Retry failed calls' by voice — just say it and Mira redials everyone whose call failed",
            "💡 Smart suggestions — drafted emails awaiting approval, idle hot leads ready to call, and more surfaced in her greeting",
        ],
    },
    {
        "date": "2026-07-24 (Hands-free Mira)",
        "changes": [
            "🎙️ Hands-free conversation mode — tap Mira (or her mic) ONCE and she keeps the conversation going: she talks, then listens for your reply automatically, again and again until your command is done. Say 'stop', 'bye' or 'thank you' to end",
            "🔴 Live listening indicator — the header shows 'Listening — just talk to me' while her ears are open",
            "🗺️ Opening the Platform Map now also starts hands-free mode — Mira gives the live update and immediately waits for your command",
        ],
    },
    {
        "date": "2026-07-24 (Neural Platform Map)",
        "changes": [
            "🌌 Platform Map reborn — neon glowing module cards connected to Miracurl HQ with sparkling animated particle streams flowing along every connection, twinkling starfield and a pulsing AI core",
            "🗣️ Mira narrates the map — on open she reports live: new leads received, payments received (with ₹ amount), new tenants added, staff registered, and 'on your behalf I called N leads — no positive response yet / X said yes!'",
            "⚡ Real-time voice alerts — while the map is open, Mira speaks new events the moment they happen (new lead, payment, booking, new salon…)",
        ],
    },
    {
        "date": "2026-07-24 (Call Recordings & Retry)",
        "changes": [
            "🎧 Call Recordings — every Mira call is now recorded; press 'Play recording' on any call in Call History to hear the actual conversation",
            "🔁 Retry Failed Calls — one button re-dials everyone whose latest call failed (skips opt-outs and leads who already said yes) — perfect after upgrading Twilio",
            "🗺️ Platform Map now speaks — open the map and Mira greets you with a live update: new leads found today (or 'none yet'), calls made, interested, bookings, then asks for your command",
        ],
    },
    {
        "date": "2026-07-23 (Call Intelligence)",
        "changes": [
            "📞 Mira Call History — new panel in the Lead Agent with every call: status, result, duration, the full CONVERSATION TRANSCRIPT, and a plain-English failure reason (e.g. 'Twilio trial: number not verified — upgrade Twilio to call anyone')",
            "🎙️ Tap Mira → instant call report — her greeting now includes today's calls, who's interested, why calls failed, and how many hot leads are still callable",
            "☎️ Call any specific number — tell Mira 'call 9876543210' or 'call Empire Hair Lounge' and she dials that exact number/salon",
            "🌙 Evening digest now goes to admin@miracurl-suite.com; failed calls show clear reasons on the Platform Map too",
        ],
    },
    {
        "date": "2026-07-23 (Evening Digest)",
        "changes": [
            "🌙 Mira's Evening Digest — every day at 7 PM IST, Mira emails you a beautiful summary: leads found today, calls made, who pressed 1 (with their phone/email so you can follow up), callbacks requested, and how many hot leads are still callable tomorrow",
        ],
    },
    {
        "date": "2026-07-23 (Voice-commanded calling)",
        "changes": [
            "🎙️ Tell Mira to call — say or type 'call the hot leads' to your HQ assistant and she replies 'You have N hot leads with phone numbers ready — how many should I call now?'. Answer '5' (or 'all') and she dials them one by one, no email needed, results appear live on the lead cards",
        ],
    },
    {
        "date": "2026-07-23 (Auto Campaign)",
        "changes": [
            "⚡ Auto Campaign — flip the 'Auto-call new hot leads' switch in the Lead Agent and Mira automatically phones every freshly discovered hot lead within the hour: business hours only (10 AM–7 PM IST), max 25 calls/day, never re-calls the same lead, honours opt-outs",
        ],
    },
    {
        "date": "2026-07-23 (Mira Conversations + Live Map)",
        "changes": [
            "🗣️ Full Conversation Mode — on outbound calls, leads can now simply SPEAK to Mira ('how much does it cost?', 'we already use other software') and she answers live using your sales script, handles objections, and closes: if the owner agrees, the demo pack + trial email goes out automatically mid-call",
            "🌌 Platform Map is now LIVE — real-time Mira call counters (calls made, today, interested, AI conversations), a Live Activity Stream (new leads, bookings, payments, new salons, staff registrations, call outcomes) refreshing every 30s, and an AI Insight card comparing this week's leads vs last week",
            "📞 Ask Mira 'how many calls did you make today?' in the HQ assistant — call stats are in her live snapshot",
        ],
    },
    {
        "date": "2026-07-23 (Mira Voice)",
        "changes": [
            "📞 Mira AI now CALLS your hot leads — one click on a lead (or 'Mira Call Hot Leads' for a batch) and Mira phones the salon, delivers your Miracurl pitch in a natural Indian-English voice, and offers: Press 1 → demo pack + 7-day trial emailed instantly · Press 2 → call back later · Press 9 → opt out. Results (Interested / Call back / Opted out) appear right on each lead card",
            "🎙️ Meet your HQ voice assistant — when you open the Super Admin console, Mira greets you out loud with today's snapshot (hot leads, bookings, revenue, expiring trials) and you can ask anything by typing or speaking: 'show hot leads', 'revenue yesterday', 'how many trials expiring?' — she answers with live data and jumps to the right tab",
        ],
    },
    {
        "date": "2026-07-23 (Gift Card Intelligence)",
        "changes": [
            "💰 Balance updates by email — every time a gift card is used at your POS, the holder instantly gets a themed email showing what was redeemed and the exact remaining balance",
            "⏰ Expiry nudges — 14 days and 3 days before a card expires unused, both the recipient AND the buyer get a friendly reminder to book and redeem",
            "🪔 Occasion auto-promotion — 7 days before Diwali, Valentine's, Mother's/Father's Day, Christmas & New Year, your customer list automatically receives a beautiful 'send a gift card' invite (once per occasion, toggle in Settings → Gift Cards)",
            "🏅 The new certificate-style relieving letters (approved design) are live in this build",
        ],
    },
    {
        "date": "2026-07-23 (Gift Cards)",
        "changes": [
            "🎁 Gift Cards are here! Customers can buy occasion gift cards (Birthday, Anniversary, Valentine's, Diwali, Christmas + 7 more) for loved ones at /gift/your-salon — with your salon logo on a beautiful themed e-card",
            "💳 Two ways to get paid: connect your own Razorpay keys OR just add your UPI ID (GPay/PhonePe) in Settings → Gift Cards; UPI orders wait for your one-tap 'Money received' confirmation",
            "📧 The e-gift card with a unique GC- code is emailed to the recipient instantly — or scheduled to arrive exactly on the special day; the buyer gets a receipt too",
            "🧾 Redeem at POS: enter the gift code at billing — balance deducts and any remainder stays on the card until it's used up (validity configurable, default 6 months)",
            "🛍️ 'Gift Card for a Loved One' buttons added on your public booking page and salon page",
        ],
    },
    {
        "date": "2026-07-23",
        "changes": [
            "🔄 'New version available' toast — after every deployment, anyone on an old browser tab sees a one-click Refresh prompt automatically (no more preview-vs-live confusion)",
            "📮 Business inboxes flow into HQ Inbox — emails to support@, billing@, payments@, sales@, booking@, careers@, info@, contact@ or admin@miracurl-suite.com now land in Super Admin → HQ Inbox tagged by inbox, with notification bell alerts",
            "⚖️ Dispute link on the Terminated banner — staff who believe a termination mark is wrong can appeal directly from the public registry; appeals arrive in HQ Inbox with their name & phone",
            "📧 Legal page contacts now use your live inboxes — Terms → admin@, Privacy → support@, Refund Policy → billing@ & payments@",
            "🔔 Staff verification now pings you — every new public 'Get verified' request, owner rating and relieving-letter request lands instantly in your Super Admin notification bell (new 🪪 Staff Verification filter)",
            "⭐ One-click owner ratings — the public badge form now collects the owner/manager's email; the owner instantly gets an email with 5 one-tap buttons (Excellent → Bad). One click records the rating on the staff's public registry profile — no more 'Not yet rated'. Sent again automatically when you mark 'Verified by Salon Owner', and re-sendable from the console",
            "📄 Relieving letters for non-Miracurl salons — the owner's email includes 'Request relieving letter'; they pick the exit type (Excellent/Standard/Terminated/Absconded) + last working date on a simple page → it lands in Staff Verification with a 'Send Relieving Letter' button → the certificate PDF is emailed to BOTH the staff member and the owner, and their registry record is closed with the right exit status",
        ],
    },
    {
        "date": "2026-07-21",
        "changes": [
            "📜 New Refund Policy page at /refund-policy — India & international refund rules, cancellations and chargebacks, linked from the website footer and Terms",
            "📧 Dedicated contact inboxes — legal@ (Terms), privacy@ (Privacy Policy), refunds@ & billing@ (Refund Policy) on miracurl-suite.com",
            "↩️ Replies come home — customer replies to reminders, receipts and booking emails now land in support@miracurl-suite.com automatically",
            "🏅 Certificate-style relieving letters — the Excellent letter is now a rose-gold certificate with your salon's own logo, decorative border, gold medal seal and a green '★ EXCELLENT' badge above the staff name; Terminated letters get a red seal + red '✖ TERMINATED' badge",
            "📧 Legal contact updated to support@miracurl-suite.com on the Privacy Policy & Terms of Service pages",
            "🩹 Fixed: clicking Privacy Policy / Terms links now opens the page from the top heading instead of mid-page",
        ],
    },
    {
        "date": "2026-07-20",
        "changes": [
            "⚠ Termination alert on QR verification — when anyone scans a staff badge or searches the public Staff Registry, a bold red 'TERMINATED / ABSCONDED by a previous employer' banner now appears at the top of the profile, so hiring salons see the red flag instantly",
            "📄 Relieving letters — from Settings → Previous Staff, owners can now issue a PDF letter on the salon letterhead (with logo & employment duration) straight to the staff member's email. Choose the type: 🌟 Excellent (served notice), ✅ Standard (resigned), 🚫 Terminated (misconduct/theft) or ⚠️ Absconded — terminated/absconded automatically lowers their rating on the public staff verification portal",
            "🩹 Fixed: staff who already left no longer appear in the 'Today's late arrivals' owner email",
            "✨ Cleaner funnel cards — the lead funnel now shows simple live counters (Leads Found, Qualified, Emails Sent, Demos, Customers) with animated sparkling icons instead of the old 'Target 300 / Done' badges",
            "🩹 No more stuck searches — if a lead search gets interrupted (e.g. by a deployment), it now auto-recovers instead of showing 'Mira is working…' forever; runs also auto-stop after 30 minutes, and there's a new ⏹ Stop button to end a run manually (leads found so far stay saved)",
            "🎯 Mira targets ALL salons again — every salon is now captured (no more skipping ones without a website). Scoring is balanced: salons already on Fresha/Vagaro/Mindbody score highest as 🔥 migration leads, while growth-stage salons (no website/booking yet) also score well as prospects who need software",
            "📈 Lead Agent ROI dashboard — Super Admin → Lead Generation now shows the full outreach funnel (contacted → replied → demo → converted), your conversion rate, and the annual revenue won per converted salon, so you see exactly what the lead agent earns you",
            "🎉 Lead-to-customer tracking — when a lead you contacted signs up for a trial with the same email, Mira auto-marks them '🟢 Customer' with a green Converted badge, so you can see the lead agent's true ROI (contacted → replied → demo → signed up)",
            "🔒 Extra security hardening — lead-finder now re-checks the real server address it connects to (blocks internal-network probing), and the reply webhook uses tamper-proof secret comparison",
            "📅 Demo Calendar auto-link — when a lead (including 🔥 Replied ones) books a demo on your /demo page or via Mira's chat, they auto-move to '🟣 Meeting scheduled' and the booked slot shows right on their lead card",
            "🔥 Reply tracker — when a lead replies to your outreach, Mira flags them '💬 Replied' automatically (via Resend inbound webhook) with a new Replied filter in the funnel; you can also mark replies manually from the status dropdown",
            "🔍 Hunt all emails — one click re-runs the deep email hunt (website → Instagram → web search) across every no-email lead, with a live progress log and auto-drafted pitches for each inbox found",
            "Indian tips, the Indian way 🇮🇳 — POS tip buttons for Indian salons are now flat ₹10/₹20/₹50/₹100/₹200/₹500 (US/UK salons keep 15–25%), and the custom amount box now shows what you type clearly",
            "Tips ledger & handover 💜 — Reports → Tips by Stylist now tracks Pending vs Paid with a one-tap 'Mark paid' button (hand cash over at day-end, weekly or monthly — your call), and every stylist sees their own Earned/Received/Pending tips in the Employee Portal, clearly separate from salary",
        ],
    },
    {
        "date": "2026-07-19 (evening)",
        "changes": [
            "🔍 Find email retry — leads with no inbox now have a 'Find email' button: Mira re-hunts with a deep website crawl, then the salon's Instagram bio, then a web search, and drafts the pitch the moment she scores a hit",
            "Lead Gen finds real inboxes 📧 — Mira now rejects fake template emails (user@domain.com etc.), decodes 'info [at] salon [dot] com' tricks, digs through contact/about/booking pages on any CMS, prefers the salon's own domain & booking/info inboxes, and drops emails on dead domains",
            "Demo before you decide 📅 — USD renewal & trial reminder emails now include a 'Book a live demo' button, so hesitant international owners can grab a 1-on-1 call instead of quietly churning",
            "Stripe payments at HQ 🏦 — Super Admin → Billing now shows every international Stripe transaction (subscriptions & booking deposits) with salon, plan, amount, status and whether it came from Settings or a renewal email",
            "Tips at billing 💜 — the POS now has one-tap tip presets (15/18/20/25% or custom) with a 'tip goes to' stylist picker; tips show on receipts, prints, emails & WhatsApp, and a new 'Tips by Stylist' report tracks who earned what (tips never mix into salon revenue)",
            "POS speaks your currency 💱 — billing screen, receipts and reports now show $/£/€ for international salons instead of ₹",
            "USD renewals on autopilot 💌 — international salons now get renewal reminder emails 15/7/5/1 days before expiry with a one-click 'Pay & Activate' Stripe link (no login needed); Indian salons keep their Razorpay reminders",
            "Pay & Activate in dollars 💳 — international salons now have a Stripe-powered USD subscription card in Settings (Starter / Professional / Premium AI, monthly / 6-month / annual); the plan activates instantly after payment, no WhatsApp back-and-forth",
            "USD pricing everywhere for international salons 💵 — the Start Trial signup now auto-detects your country and shows dollar pricing (with a 🇮🇳/🌍 toggle), and international salons are created with USD currency from day one",
            "Graceful goodbyes 🌸 — deactivated or departed staff now see a warm 'Thank you for everything' farewell screen on both the salon app login and the Employee Portal, instead of a cold error message",
            "Staff exits close themselves 🕐 — once a staff member's last working day passes, the system automatically marks them as left, blocks their login and stamps the exit date on their public registry history (no manual entry ever again)",
            "Previous staff list in Settings ♻️ — departed staff are kept in a new Settings card for 6 months with one-tap Rehire (fresh staff ID, same permanent registry history — both stints show on their public profile) and a delete option",
            "Auto-approve returning stylists 🪄 — when someone signs up with an email matching your staff profile, they appear in a 'Pending sign-ups' panel on the Staff page for one-tap approve & auto-link",
            "Auto win-back is here 💌 — flip the 'Auto' switch on the Win-them-back card and Mira emails lapsed guests (45+ days) a personal comeback offer daily, capped at 15/day with a 30-day cooldown",
            "Weekly digest on WhatsApp 📲 — a new dashboard card shows last week's revenue, bills, top service & new guests with a one-tap 'Share on WhatsApp' button",
            "Staff privacy control 🛡 — staff can withdraw (or restore) consent for public registry lookups with one tap in their Employee Portal",
            "Lead Gen went global 🌍 — Mira now searches Salons, Unisex Salons, Spas, Boutiques & Hair Care studios in parallel, digs 15× deeper in big cities, rotates through fresh localities every run, works for cities worldwide ('London, UK') and quotes USD pricing to international leads automatically",
            "Cleaner targets 🎯 — Lead Gen counters past their goal now show a green '✓ TARGET DONE' chip instead of confusing overflow numbers",
        ],
    },
    {
        "date": "2026-07-19",
        "changes": [
            "Mira books reliably now 🔒 — fixed a bug where Mira sometimes said 'that slot is booked' even when it wasn't (an internal service-ID mix-up); bookings now go through first time",
            "Mira lives on Indian time 🕐 — she never offers time slots that have already passed today, resolves 'today/tomorrow/evening' in IST correctly, and knows every open slot for the next 7 days",
            "One confirmation, then booked ✅ — Mira collects name, phone, service, expert & time, shows one summary, and books the moment you say yes — no more double-checking loops",
            "Speak English, get English 🗣 — Mira now strictly mirrors your language (pure English for English, Hindi for Hindi, Kannada for Kannada), voice messages are transcribed in the right script, and she never refuses mixed or garbled voice messages",
            "Booking replies in your language 💬 — even system messages (booking confirmed, slot unavailable, alternatives offered) now arrive in English, Hindi or Kannada to match your chat",
            "Honest slot answers 🙏 — if your chosen expert is busy, Mira tells you exactly that (e.g. 'Rahul is already booked at that time') and offers the times that are genuinely free",
            "Booking flood protection 🛡 — AI bookings are now capped (8 per visitor per 10 minutes + a daily per-salon ceiling) so bots can never flood your calendar; real guests are politely asked to call if the cap is hit",
            "Mira's new logo everywhere ✦ — the Mira AI avatar was redrawn as a perfect, crisp circle and now renders beautifully on the /demo page, chat widgets and voice bubbles",
            "Super Admin: Staff Verification section 🪪 — 'Get verified' requests from external stylists now land in their own Staff Verification tab (not Tenant Inquiries) with every detail + the stylist's photo: call the owner → mark 'Verified by Salon Owner' → 'Generate Badge & Email' creates their permanent Staff ID (STF-xxxxx), emails the badge PDF and offers portal download",
            "Get Verified form upgraded 📸 — external stylists now upload a recent photo (appears on their badge) and share their total experience along with salon, owner contact and joining date",
            "Scan-to-verify badges 📱 — every verified badge PDF now carries a QR code that opens the stylist's live registry profile, so any salon can verify them in one scan",
        ],
    },
    {
        "date": "2026-07-18",
        "changes": [
            "Mira found her voice 🎙 — the booking chat now speaks: auto-greeting when opened, spoken booking confirmations, graceful silent fallback, a WhatsApp share button, and full Kannada support alongside English & Hindi",
            "The /demo page got the couture treatment 🖤 — dark rose-gold redesign with Mira AI front and center, mobile layouts fixed",
            "Mira Inquiries inbox 💌 — when Mira recommends products or takes a query in chat, it lands in a new 'Mira Inquiries' tab on your Messages page with the full transcript",
            "Staff Portal emails redesigned ✉️ — attendance and portal emails now carry premium Miracurl branding",
            "Super Admin: Lead follow-up command bar 🚀 — every 'Already sent' lead in Mira Lead Agent now has the full toolkit: status dropdown (Contacted → Meeting scheduled → Customer), 🔔 one-tap Remind (works for ALL sent leads, opened or not), 📩 Resend PDF, 🎥 Google Meet invite with calendar (.ics) attachment, and quick 📞 Call / 💬 WhatsApp buttons",
            "Super Admin: Demo time-picker with timezone smarts 📅 — send prospects a 'pick your demo time' email from the Lead Agent or Demo Campaign; when they book, you see the slot in IST AND their local time side-by-side",
            "Super Admin: 5-day auto follow-ups 🔁 — Mira automatically nudges leads who haven't replied after 5 days, with the full screens-tour PDF attached to every outreach email",
            "Super Admin: International pricing goes live 🌍 — the landing page now has an India ₹ / International $ toggle with dedicated USD plans (Starter/Professional/Premium/Enterprise), and outreach emails automatically quote USD for non-India leads",
            "Super Admin: Demo invite tracking is now scanner-proof 🛡 — corporate email security bots no longer trigger false 'Demo requested' alerts; only a real slot booking counts (link fetches show as a subtle 'Clicked' badge instead)",
            "Smart Review funnel for walk-ins ⭐ — customers scan your desk QR tent card → rate → Mira writes their Google review → one tap copies & opens Google. Unhappy ratings (1-3★) go privately to you, never public",
            "Review funnel analytics on your dashboard 📊 — see QR scans → ratings → happy customers → sent-to-Google conversions with average rating, right on the Reviews page",
            "E-receipts got smarter 🧾 — every receipt email and WhatsApp message now carries your smart review link, and the printable review tent card is auto-attached",
        ],
    },
    {
        "date": "2026-07-17",
        "changes": [
            "HD Designer Booking QR posters 🖼️ — beautiful print-ready posters with your salon's booking QR, plus A5 desk tent cards for reviews",
            "Original legal pages ⚖️ — professionally written Terms of Service & Privacy Policy, styled to match the brand",
            "Inventory split: Retail vs In-house 📦 — retail products (sold with commission) and in-house consumables (used by services) now live in separate tabs with independent low-stock tracking",
            "Edit invoices with a full audit trail ✏️ — owners can correct billed invoices; every change is logged with who/when/what",
            "Mira Presenter video mode (FREE) 🎬 — generate promo videos with Mira as your avatar presenter, no external API cost",
            "AI CCTV & Hire Staff pages redesigned in the light theme, and the login/signup pages are now perfectly centered",
            "Gallery uploads fixed end-to-end 📸 — photos you upload now appear instantly on your public salon page",
            "Super Admin: Lead Agent filter buckets (Recent search / Hot leads / Ready to send / Opened / No email / Already sent) + demo calendar",
            "Platform: performance & security hardening — fixed event-loop blocking that caused intermittent Cloudflare 520 errors in production",
        ],
    },
    {
        "date": "2026-07-16",
        "changes": [
            "Under-the-hood quality & security hardening 🔧 — code health pass across the whole backend: complex functions simplified, test-suite security hygiene (no fixed passwords, crypto-safe randomness), cleaner comparisons and type hints. Nothing changes for you — everything just gets safer and easier to maintain",
        ],
    },
    {
        "date": "2026-07-15",
        "changes": [
            "Managers now see the FULL menu 👔 — Staff, Attendance, AI CCTV, Hire Staff, Messages and Settings are all visible with a small gold lock. Opening a locked section asks for the Admin PIN, and every attempt (opened, denied, unlocked) is recorded",
            "New 'Staff Activities' section 🔍 — a PIN-protected audit log where owners can see exactly which manager tried to open what and when, with denied/unlocked badges",
            "'Made with Mira ✦' gallery 🖼️ — the Studio homepage now shows the latest live websites built by real users (with live mini-previews). Instant social proof that turns visitors into builders",
            "Mira Studio is now a true chat experience 💬 — type your request, watch 'Agent is working…' and get 'Agent is finished ✦' bubbles for every build and change, with the live preview beside the chat. Changes now apply in the background too (no more timeouts on slow edits!)",
            "Power tools after every build 🧰 — upload your own photos (📎 in chat) to place on your website, run a one-tap Security Check 🛡 or Code Review 📋 on the generated code, and Push to GitHub with your personal access token (never stored)",
            "New Super Admin tab: Mira Studio Users 🎁 — see every studio builder with credits & build counts, gift free credits to anyone (they get a beautiful 'A gift for you ✦' email), and send one-tap win-back emails ('Hey Bablu, you're one sentence away ✦') with a recharge link to bring back users who left without building",
            "Mira Studio websites got a quality overhaul 🖼️ — every photo now comes from a verified library matched to your business (watch stores get watches, clinics get clinics!), no more broken images; section headings adapt too ('Our Collection' for stores, 'Our Menu' for restaurants). Even websites you already built get auto-repaired",
            "Studio preview fixed + deploy options added 🚀 — the live preview now loads inside the studio, and every built website shows 3 clear deployment paths: hosted-by-Mira link, free self-hosting (Netlify/Vercel drag-drop), or your own custom domain",
            "Mira AI Studio now on the homepage 🏠 — a golden '✦ Mira AI Studio' link in the top menu plus a stunning 'Built with AI' showcase section with a live animated demo (watch a prompt turn into a website!) so visitors can discover the Studio and grab their 50 free credits",
            "Introducing Mira AI Studio ✦ (/mira.ai) — a brand-new platform where anyone can build a full website or business app from one sentence! Sign up for 50 free credits, watch Mira's agent team plan → design → code → test → deploy, get a LIVE URL in ~60 seconds, refine with prompts and download the full code. Credit top-ups via Razorpay",
            "Mira AI Studio wears couture 👗 — the studio page got a luxury redesign: gold & rose gradients, elegant serif headlines, glowing prompt box and a premium builder showcase that matches the Miracurl brand",
            "Your booking page just got smarter 💇 — guests now filter services by Everyone / Women / Men, and Mira's gender tags make sure men only see men's + unisex services (and vice-versa). Faster booking, fewer drop-offs",
            "One beautiful banner per category 🖼️ — no more uploading a photo for every single service! Each category (Skin, Manicure, Men Hair…) now has an elegant banner on the booking page with services as clean rows beneath. We've pre-loaded gorgeous defaults for all categories — change any of them from Service Menu → Banner",
            "Fully tune Mira's daily offer before posting 🎛️ — swap, remove or add services right on the suggestion card (tap ✕ on a service, or '+ Add / swap service'), and every price updates instantly with your chosen discount",
            "Package Builder upgrades 🎁 — Mira now picks gender-correct services (men's packages only get men's + unisex services, women's likewise), and a new '✎ Adjust %' under the package price lets you fine-tune the bundle discount with live price recalculation before publishing",
            "Service Menu redesigned ✨ — no more endless scrolling: instant search, one-tap category chips, and compact rows with quick online-booking toggles make editing your menu effortless",
            "Tune Mira's offer before you post it ✎ — a new 'Adjust %' selector on the Offer of the Day card lets you change the discount and see every service price recalculate instantly; tap 'Yes — use this offer' and the poster, caption and offer text are all rebuilt with YOUR chosen %",
            "Every email now carries your brand ✦ — all outgoing emails (reports, birthday wishes, review requests, alerts) end with a 'Book Now' button and a 'Powered by Miracurl' footer, turning every email into a booking opportunity",
            "Under the hood: engine room reorganised 🔧 — the backend was split from one giant file into 22 clean, domain-focused modules (customers, staff, billing, public booking, schedulers…). Nothing changes on screen, but future features ship faster and safer",
            "Locked out? Reset yourself 🔑 — 'Forgot Password' now emails a secure 1-hour reset link; setting a new password also clears any login lock instantly. Owners can still reset staff passwords from the Staff page",
            "Late staff auto-alerts ⏰ — 10 minutes after shift start with no check-in, staff get an automatic 'You're running late' email + a red banner and popup in their Staff Portal; owners receive a midday summary of the day's late arrivals",
        ],
    },
    {
        "date": "2026-07-14",
        "changes": [
            "HQ Security Snapshot 🛡️ — Super Admin's Security tab now shows a 7-day table of failed logins, PIN failures, PIN lockouts and rate-limit hits across ALL salons, with per-salon totals and a live event feed",
            "Security hardening 🛡️ — wallet balance check now needs the exact 10-digit number (with tighter limits) and shows only the balance; referral bonus crediting is race-proof; the test-data cleaner never touches customers with wallet money or invoices",
            "📣 Refer a salon, earn ₹1,000 ✦ — know a salon owner? Tap 'Share & earn ₹1,000' on your Dashboard's Miracurl Circle card and WhatsApp them your personal link. The moment they join Miracurl, ₹1,000 lands in your Circle bonus wallet!",
            "Referral amounts are now PIN-protected 🔒 — both the Miracurl Circle wallet and the Refer & Earn section in Settings need your Owner PIN before showing balances",
            "Miracurl Circle ✦ referral program — when a salon joins Miracurl through YOUR booking page, you earn ₹1,000! A PIN-protected Circle bonus wallet on your Dashboard shows earnings, and you get a congratulations email the moment your referral converts",
            "Leads now carry their source — HQ sees exactly which salon (and owner) referred every demo request, and the demo form greets visitors with 'As seen at [your salon]'",
            "Success Stories page 🌟 — a public marketing page (/success-stories) with live platform stats, salon win stories, real guest reviews and a free-demo request form that lands straight in the HQ Leads inbox",
            "Every booking page now sells for you 💼 — the footer says 'Powered by Miracurl — get this for your salon ✦' and links to the Success Stories page, turning every salon's guests into Miracurl leads",
            "Guest details are now validated ✅ — booking names accept letters only and mobile numbers must be a real 10-digit Indian number (+91 handled automatically), keeping your CRM clean",
            "Super Admin: Clean test data 🧹 — a per-salon cleanup tool scans for dummy bookings & customers (test names / invalid numbers), shows a preview, and removes them in one tap",
            "Fixed: the Day / Upcoming / Week buttons on Appointments (and Review filters) turned invisible when hovered — labels now stay readable with a clean white highlight",
            "About-Us shop poster 🏪 — new A4 print poster in the Flyer Studio: hero model, your logo, your salon story, 3 circular photos (from your gallery, or Mira creates them) and booking details",
            "Fixed: 'Have a wallet with us? — Check balance' on the public booking page wasn't responding — it now shows the guest's salon credit instantly",
            "Posters got a designer upgrade 🎨 — your salon LOGO now sits in a gold medallion on every poster, with an elegant script 'Exclusive Offer' flourish, serif headlines, a rotated '% OFF' starburst badge, sweeping ribbon curves and a styled contact bar",
            "Manage live packages 📋 — the Package Builder now shows exactly which packages are LIVE on your booking page (with a live counter), and one tap removes any of them so you can post an updated one",
            "Max 4 packages rule ✋ — your booking page never shows more than 4 packages; publishing a 5th is blocked until you remove one, keeping the page clean and focused",
            "Share the poster, not just words 📲 — 'Share on WhatsApp' now sends the glamour poster WITH the caption (on phones it opens the native share sheet; on desktop the poster downloads and WhatsApp opens ready to paste)",
            "Offer Maker quick-sets ⚡ — one tap applies 10-50% off to ALL selected services, and 3d/4d/7d/15d/30d chips fill the 'Valid till' date automatically",
            "Glamour posters 💗 — 6 stunning new AI poster styles (Pink Glam, Royal Gold, Bridal Blush, Emerald Luxe, Men's Edge, Festive Sparkle) with real model photography, your prices and booking link overlaid pixel-perfect",
            "Pick your poster look 🎨 — a style selector on the Day Offer card, Package Builder and Flyer Studio; leave it on 'surprise me' and Mira picks a fresh design each time",
            "Mira greets you with today's offer 📅 — the moment you open your Dashboard, Mira has already designed today's offer suggestion; just tap 'Yes — use this offer' to publish or 'Suggest another'",
        ],
    },
    {
        "date": "2026-07-13",
        "changes": [
            "Smarter review rewards ⭐ — 5★ reviews now earn ₹30 credit, 4★ earn ₹20 (auto-applied on the next visit), with a 'make it 5★ for ₹30' nudge",
            "Mira pre-writes the review ✍️ — tap 4★ or 5★ and Mira instantly drafts a personal comment from the guest's actual service & stylist; fully editable, and it doubles as their Google review after submit",
            "Monday auto-package suggester 📅 — when your package expires, Mira drafts a fresh one every Monday (audience rotates Men → Women → Family) and emails you; you approve & publish when ready — nothing goes live without your OK",
            "You control the offer 🎛️ — pick the exact discount % (5-50%) and the service tier (Premium: Color, Keratin, Botox / Budget crowd-pullers) before asking Mira; she calculates prices from YOUR choice",
            "Mira auto-rhythm 🧠 — left on 'Mira picks'? She reads your footfall: budget crowd-pullers when visits drop, premium high-margin deals on lean weekdays",
            "One tap = 3 platforms 🚀 — accepting a Day Offer (or publishing a Package) now auto-posts to Google Business, Instagram AND Facebook, with the flyer image",
            "Change offer & New poster — locked today's offer by mistake? Tap 'Change offer' to regenerate, or 'New poster' for a fresh flyer design without changing the offer",
            "Mira Package Builder 🎁 — one tap creates a Men's / Women's / Family package from your real menu, with your % and a validity window (3/4/7/15/30 days); expired packages vanish from the booking page automatically",
            "Your booking page sells more 💸 — signature packages & today's offer are now bookable in one tap, with a live 'Ends in 6h 32m' countdown and a wallet-balance checker for guests",
            "Prepaid Wallet / Membership 💳 — sell top-up plans (pay ₹5,000 → get ₹6,000 credit), track balances per customer, and bill against 'Salon Wallet' at the POS",
            "Birthday & Anniversary auto-offers 🎂 — wishes go out automatically with your gift offer; the dashboard shows today's celebrations with one-tap WhatsApp & SMS",
            "Staff targets & leaderboard 🏆 — set a monthly target + % per stylist; hit the target and the commission on their full business lands in the salary slip automatically",
            "Rate-your-visit funnel ⭐ — happy guests (4-5★) get a Mira-written Google review to paste in one tap; unhappy guests (1-3★) go to a PIN-locked private Complaints panel — never to Google",
            "Post History 📊 — new tab in Mira Studio showing every auto-post with its Instagram/Facebook likes & comments, so you know which offers pull customers",
            "Fixed: flyer posters on the live server had tiny text and broken ₹ symbols — fonts are now bundled with the app",
            "Fixed: public offer banner showed ₹0 as the original price",
            "Security hardening 🛡️ — daily AI usage quotas & durable rate limits on public endpoints, encrypted social-media tokens, and pinned OAuth redirect hosts",
        ],
    },
    {
        "date": "2026-07-12",
        "changes": [
            "Your public salon page got a glow-up ✨ — 3D floating lights, sparkles and neon service cards. Share miracurl-suite.com/salon/your-salon-name and impress every client before they even walk in",
            "Two apps, clearly split 📱 — customers installing from your booking/salon page now get the violet 'Miracurl Book' app; your business dashboard stays the emerald 'Miracurl Partner' app",
            "Hiring payments, automated 💰 — when a hired candidate's login is created, HQ is notified instantly and the salon owner receives a Razorpay payment link for the placement fee (amount now configurable by HQ)",
            "My Resume builder 📄 — Employee Portal staff fill their skills & experience once and download a polished PDF resume, with their verified Miracurl history included automatically",
            "Employee Portal 🧑‍💼 — registry-verified staff can now self-register at /employee with their mobile + Aadhaar, manage their profile, see employment history and apply to openings at any Miracurl salon",
            "Win them back 💌 — your dashboard now shows customers who haven't visited in 45+ days, with a one-tap WhatsApp nudge (pre-written message + 15% off) and a 30-day snooze",
            "Super Admin: Lead Gen Email 📬 — invite prospect salons to a demo with a designed email (12-agent AI team, live pricing, brochure + policy PDFs attached), open/click tracking, funnel stats and one automatic 5-day follow-up nudge",
            "Super Admin: Demo scheduler 📅 — prospects pick their preferred slot on a branded page; both sides get Google Calendar invites, and HQ gets a 🔥 notification + email",
            "Super Admin: Documents Center — download & share the tenant onboarding pack (Onboarding Policy, Hiring Policy, Suite Overview, T&C) as branded PDFs; the Suite Overview brochure now auto-attaches to every welcome email",
            "Super Admin: Platform Earnings chart — subscriptions + placement fees combined, last 6 months, with dues indicator",
            "Platform: security audit round 3 passed ✅ — CSV export hardening and rate-limited public tracking endpoints",
            "Marking a staff member as 'Left' now instantly blocks their salon app login (they keep access to the Employee Portal)",
            "Fixed: Mira's voice now stops speaking the moment you log out",
            "Mobile fix — the app header no longer overflows on phones: compact branch selector, icon-only salon switcher, and horizontal-scroll protection across every page",
        ],
    },
    {
        "date": "2026-07-11",
        "changes": [
            "Your salon now has its own public web page ✨ — share miracurl-suite.com/salon/your-salon-name with clients: your services & prices, star rating and best reviews, plus a Book Now button. Google can find and rank it too",
            "Super Admin: Notifications center — every hiring update, owner message, software lead, renewal alert and new signup in one filterable feed, with a jump-to-section on click",
            "Super Admin: the HQ console got a subtle 3D animated backdrop — floating orbs, rings and sparkles",
            "Platform: SEO pass — robots.txt, sitemap.xml (now including every salon's public page) and structured data for Google",
            "Platform: code-quality pass — Mira AI helpers extracted to a shared module (circular import eliminated), and 5 oversized functions (flyer composer, HQ ID card, receipt totals, salon signup, HQ digest email) refactored into small, testable units",
            "Platform: security audit round 2 — CCTV snapshot fetch now re-validates the connected IP (blocks DNS-rebinding SSRF), pending staff sign-ups are scoped per salon, and credential emails are HTML-escaped",
            "Platform: website — new neon 3D 'software flow' timeline on the landing page: the 7-step Miracurl journey from signup to auto-pilot revenue, with glowing animated cards",
            "Hire Staff 🧑‍💼 — post a hiring request from your dashboard and Miracurl HQ finds you verified candidates, schedules trials and updates you at every step",
            "Public Jobs board (/jobs) — HQ-verified professionals apply for open positions with their registered number; salon identity stays private until shortlisting",
            "Flash offers ⚡ — when AI CCTV spots chairs sitting empty, Mira alerts you on the Dashboard and designs a 2-hour flash offer with poster + WhatsApp caption in one tap",
            "What's New ✨ popup — after every update, salon owners see the latest features once, with a WhatsApp share button",
            "Renewal reminders on auto-pilot — owners get a branded email 15, 7 and 1 day(s) before their subscription/trial ends, with a direct Razorpay renew link",
            "Refer & Earn: referral list now shows reward status — pending until the referred salon makes its first payment, then ₹1,000 credited",
            "Mira Day-Smart Offers — ask Mira for today's offer: weekday-aware (fills chairs Mon-Thu, upsells Fri-Sun), built from your real service catalog, downloadable poster",
            "AI CCTV Analytics — waiting customers, empty chairs, queue length & idle staff read from camera frames every few minutes, with hourly trends",
            "Super Admin: Hiring tab (middleman pipeline: applied → shortlisted → trial → hired), renewals auto-email log with WhatsApp follow-ups, full Referral Tracking table",
        ],
    },
    {
        "date": "2026-07-10",
        "changes": [
            "Promo Video: Express mode now renders in seconds (was minutes / timing out on the live server)",
            "Promo Video: live timer — see exactly when generation started, how long it's running, and how long it took",
            "Promo Video: download history panel is now always visible on the right, with per-video Download & Delete",
            "Miracurl Team: new section for your own HQ staff & CEO — rose-gold company ID cards (MC-0001 style)",
            "Staff Verification: record staff of salons not using the software — public ✦ HQ Verified gold badge",
            "Staff Registry: salon owners can mark staff as 'Left salon' — moves to Past Staff, stays publicly verifiable",
            "Employee ID Cards: print-ready PDF cards for salon staff & verified staff, with blood group, barcode and a SCAN-TO-VERIFY QR code",
            "Billing: subscription plan catalog is now editable — change plan names & prices any time",
            "Deployments: this deployment history section, with server build status (compare live vs preview)",
            "Promo Video: Express now renders all scenes in a single ultra-light ffmpeg pass at social-friendly resolution — built for slow production CPUs",
            "Promo Video: AI Scenes mode fixed on the live server — renders at social resolution with low CPU priority so the server stays healthy mid-render",
            "Pricing: the public website pricing section now shows live prices from the plan catalog — edit a price in Billing and the website updates instantly",
            "Promo Video: new 'AI Booking demo' video — live walkthrough of Mira booking a Botox appointment (service, time, name) on the real app",
            "AI Posters: delete button next to download; website demo carousel refreshed with current app screens incl. Mira booking",
            "Website: partner testimonials are now real & editable from Super Admin → Partners",
            "Super Admin: new Diagnose tool per salon — see DB health, heavy data & stuck jobs, then 'Clear cache & auto-fix' remotely wipes the salon's device cache on next open",
        ],
    },
    {
        "date": "2026-07-09",
        "changes": [
            "Promo videos: removed email flow — direct download & delete from the studio",
            "AI Posters: contact details & website printed on generated posters; new AI Flyer studio for salons",
            "Platform: global API speed-up with GZIP compression",
            "Super Admin: Platform Load monitor and Database cleanup panels",
            "Mira Auto-Pilot: Monday marketing fully autonomous — weekly promo reel + AI poster auto-published to Meta",
        ],
    },
    {
        "date": "2026-07-08",
        "changes": [
            "Rose-gold rebranding across the app — new logo, favicon and downloadable Brand Kit PDF",
            "Dashboard aurora background animations",
            "Fixed promo video 'stuck forever' bug with automatic stale-job recovery",
            "Passed 2 security audits — security trust badges added to the /partner landing page",
        ],
    },
]
