"""Iteration 6 regression tests:
- /api/reports/sales generator variable (`inv`) at server.py:906
- /api/public/book/{slug} validator variable (`dt`) at server.py:~950
- Multi-tenant isolation regression (super_admin vs tenant admin scoping)
- Login as admin@miracurl.com returns token
"""
import os
import pytest
import requests
from datetime import datetime, timezone, timedelta

BASE_URL = os.environ["REACT_APP_BACKEND_URL"].rstrip("/")
API = f"{BASE_URL}/api"

ADMIN_EMAIL = "admin@miracurl.com"
ADMIN_PASS = "Miracurl@123"
SUPER_EMAIL = "super@miracurl.com"
SUPER_PASS = "Super@Miracurl123"
ELEGANCE_EMAIL = "owner@elegance.com"
ELEGANCE_PASS = "Owner@123"
DEFAULT_SLUG = "miracurl-marathahalli"
ELEGANCE_SLUG = "elegance-koramangala"


def _login(email, password):
    r = requests.post(f"{API}/auth/login", json={"email": email, "password": password})
    assert r.status_code == 200, f"login failed {email}: {r.status_code} {r.text}"
    return r.json()["access_token"]


@pytest.fixture(scope="module")
def admin_token():
    return _login(ADMIN_EMAIL, ADMIN_PASS)


@pytest.fixture(scope="module")
def super_token():
    return _login(SUPER_EMAIL, SUPER_PASS)


@pytest.fixture(scope="module")
def elegance_token():
    return _login(ELEGANCE_EMAIL, ELEGANCE_PASS)


# ---- Auth regression ----
class TestAuthRegression:
    def test_admin_login_returns_token(self):
        r = requests.post(f"{API}/auth/login", json={"email": ADMIN_EMAIL, "password": ADMIN_PASS})
        assert r.status_code == 200
        data = r.json()
        assert "access_token" in data
        assert isinstance(data["access_token"], str) and len(data["access_token"]) > 20
        assert data["user"]["email"] == ADMIN_EMAIL


# ---- Sales report regression (inv generator at line 906) ----
class TestSalesReport:
    def test_sales_returns_valid_totals(self, admin_token):
        r = requests.get(
            f"{API}/reports/sales",
            headers={"Authorization": f"Bearer {admin_token}", "X-Tenant-Slug": DEFAULT_SLUG},
        )
        assert r.status_code == 200, r.text
        d = r.json()
        # Validate the keys generated by the `inv` generator at line 906
        assert "total_invoices" in d
        assert "total_revenue" in d
        assert "by_payment_mode" in d
        assert "invoices" in d
        assert isinstance(d["total_invoices"], int)
        assert isinstance(d["total_revenue"], (int, float))
        assert d["total_revenue"] >= 0
        assert isinstance(d["by_payment_mode"], list)
        # Cross-verify: sum of by_payment_mode == total_revenue (within rounding)
        if d["by_payment_mode"]:
            mode_sum = round(sum(m["amount"] for m in d["by_payment_mode"]), 2)
            assert abs(mode_sum - d["total_revenue"]) < 0.5, \
                f"Mode breakdown {mode_sum} != total {d['total_revenue']}"

    def test_sales_with_date_range(self, admin_token):
        today = datetime.now().strftime("%Y-%m-%d")
        r = requests.get(
            f"{API}/reports/sales",
            params={"start": "2024-01-01", "end": today},
            headers={"Authorization": f"Bearer {admin_token}", "X-Tenant-Slug": DEFAULT_SLUG},
        )
        assert r.status_code == 200, r.text


# ---- PublicBookingIn.scheduled_at validator regression (dt at line ~950) ----
class TestPublicBookingValidator:
    def _services(self):
        r = requests.get(f"{API}/public/services/{DEFAULT_SLUG}")
        assert r.status_code == 200
        return r.json()

    def _unique_phone(self):
        ts = int(datetime.now().timestamp() * 1000) % 10**8
        return f"82{ts:08d}"

    def test_valid_future_iso_accepted(self):
        svcs = self._services()
        # 14:00 IST tomorrow
        ist = datetime.now(timezone(timedelta(hours=5, minutes=30))) + timedelta(days=1)
        ist = ist.replace(hour=14, minute=0, second=0, microsecond=0)
        r = requests.post(f"{API}/public/book/{DEFAULT_SLUG}", json={
            "customer_name": "TEST_Iter6Future",
            "customer_phone": self._unique_phone(),
            "service_ids": [svcs[0]["id"]],
            "scheduled_at": ist.isoformat(),
        })
        # Either accepted or rate-limited from earlier runs
        assert r.status_code in (200, 429), r.text
        if r.status_code == 200:
            assert "appointment" in r.json()
            # cleanup
            try:
                tok = _login(ADMIN_EMAIL, ADMIN_PASS)
                requests.delete(
                    f"{API}/appointments/{r.json()['appointment']['id']}",
                    headers={"Authorization": f"Bearer {tok}", "X-Tenant-Slug": DEFAULT_SLUG},
                )
            except Exception:
                pass

    def test_past_iso_rejected(self):
        svcs = self._services()
        past = (datetime.now(timezone.utc) - timedelta(hours=3)).isoformat()
        r = requests.post(f"{API}/public/book/{DEFAULT_SLUG}", json={
            "customer_name": "TEST_Iter6Past",
            "customer_phone": self._unique_phone(),
            "service_ids": [svcs[0]["id"]],
            "scheduled_at": past,
        })
        assert r.status_code in (422, 429), r.text
        if r.status_code == 422:
            assert "future" in r.text.lower()

    def test_invalid_iso_rejected(self):
        svcs = self._services()
        r = requests.post(f"{API}/public/book/{DEFAULT_SLUG}", json={
            "customer_name": "TEST_Iter6Bad",
            "customer_phone": self._unique_phone(),
            "service_ids": [svcs[0]["id"]],
            "scheduled_at": "not-an-iso-date",
        })
        assert r.status_code in (422, 429), r.text
        if r.status_code == 422:
            assert "iso" in r.text.lower() or "invalid" in r.text.lower()


# ---- Multi-tenant isolation regression ----
class TestMultiTenantIsolation:
    def test_admin_scoped_to_own_tenant(self, admin_token):
        """Tenant admin sees only their tenant's customers."""
        r = requests.get(
            f"{API}/customers",
            headers={"Authorization": f"Bearer {admin_token}"},
        )
        assert r.status_code == 200
        # Should return list (may be empty or have only this tenant's customers)
        assert isinstance(r.json(), list)

    def test_admin_cross_tenant_forbidden(self, admin_token):
        """admin@miracurl.com using X-Tenant-Slug=elegance must get 403."""
        r = requests.get(
            f"{API}/customers",
            headers={
                "Authorization": f"Bearer {admin_token}",
                "X-Tenant-Slug": ELEGANCE_SLUG,
            },
        )
        assert r.status_code == 403, f"Expected 403, got {r.status_code} {r.text}"

    def test_super_admin_can_scope_via_header(self, super_token):
        """Super admin can read tenant A's data via X-Tenant-Slug."""
        r1 = requests.get(
            f"{API}/customers",
            headers={"Authorization": f"Bearer {super_token}", "X-Tenant-Slug": DEFAULT_SLUG},
        )
        r2 = requests.get(
            f"{API}/customers",
            headers={"Authorization": f"Bearer {super_token}", "X-Tenant-Slug": ELEGANCE_SLUG},
        )
        assert r1.status_code == 200, r1.text
        assert r2.status_code == 200, r2.text

    def test_tenants_current_returns_own_tenant(self, admin_token, elegance_token):
        r1 = requests.get(
            f"{API}/tenants/current",
            headers={"Authorization": f"Bearer {admin_token}"},
        )
        r2 = requests.get(
            f"{API}/tenants/current",
            headers={"Authorization": f"Bearer {elegance_token}"},
        )
        assert r1.status_code == 200 and r2.status_code == 200
        assert r1.json()["slug"] == DEFAULT_SLUG
        assert r2.json()["slug"] == ELEGANCE_SLUG

    def test_super_admin_overview_accessible(self, super_token):
        r = requests.get(
            f"{API}/super-admin/overview",
            headers={"Authorization": f"Bearer {super_token}"},
        )
        assert r.status_code == 200
        d = r.json()
        assert "total_tenants" in d or "tenants" in d or isinstance(d, dict)

    def test_super_admin_endpoint_forbidden_for_admin(self, admin_token):
        r = requests.get(
            f"{API}/super-admin/overview",
            headers={"Authorization": f"Bearer {admin_token}"},
        )
        assert r.status_code == 403, r.text
